name: Package WordPress Plugin

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set plugin version
        run: echo "PLUGIN_VERSION=1.0.0" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          mkdir -p dist
          zip -r dist/my-plugin-${{ env.PLUGIN_VERSION }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/my-plugin-${{ env.PLUGIN_VERSION }}.zip
