name: Package WordPress Plugin

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          mkdir -p dist
          zip -r dist/my-plugin.zip .
        env:
          PLUGIN_VERSION: ${{ github.run_number }}

      - name: List files
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/my-plugin.zip
