name: Package WordPress Plugin

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read plugin version
        id: read_version
        run: |
          PLUGIN_VERSION=$(cat version.txt)
          echo "::set-output name=version::$PLUGIN_VERSION"

      - name: Create ZIP file
        run: |
          mkdir -p dist
          zip -r dist/my-plugin-${{ steps.read_version.outputs.version }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/my-plugin-${{ steps.read_version.outputs.version }}.zip
