name: Package WordPress Plugin

on:
  push:
    branches:
      - release  # Cambia 'release' por el nombre de la rama que desees usar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualiza a v3 para Node.js 20

      - name: Create ZIP file
        run: |
          VERSION=$(cat version.txt)
          mkdir -p dist
          zip -r dist/my-plugin-${VERSION}.zip .
        env:
          VERSION: ${{ env.PLUGIN_VERSION }}

      - name: List files
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Actualiza a v4 para Node.js 20
        with:
          name: plugin-zip
          path: dist/my-plugin-*.zip
