name: Package WordPress Plugin

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read plugin version
        id: get_version
        run: |
          PLUGIN_VERSION=$(sed -n 's/^VERSION=\(.*\)/\1/p' version.txt)
          echo "::set-output name=version::$PLUGIN_VERSION"

      - name: Create ZIP file
        run: |
          PLUGIN_VERSION=$(echo "${{ steps.get_version.outputs.version }}")
          mkdir -p dist
          zip -r dist/my-plugin-${PLUGIN_VERSION}.zip .
        shell: bash

      - name: List files
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/my-plugin-*.zip
